Config = {}
Config.Locale                     = 'en'

Config.SpawnZombie = 2500
Config.MinSpawnDistance = 50
Config.MaxSpawnDistance = 100
Config.DespawnDistance = 500

Config.ZombieDropLoot = true
Config.ProbabilityWeaponLoot = 8 
Config.ProbabilityItemLoot = 33
Config.ProbabilityMoneyLoot = 43 

Config.WeaponLoot = {
	"WEAPON_PISTOL",
	"WEAPON_FLASHLIGHT",
	"WEAPON_MACHETE",
	"WEAPON_NIGHTSTICK",
	"WEAPON_BAT",
	"WEAPON_STUNGUN",
	"WEAPON_MICROSMG",
	"WEAPON_PUMPSHOTGUN",
	"WEAPON_ASSAULTRIFLE",
	"WEAPON_SPECIALCARBINE",
	"WEAPON_SNIPERRIFLE",
	"WEAPON_FIREWORK",
	"WEAPON_FIREEXTINGUISHER",
	"WEAPON_BALL",
	"WEAPON_SMOKEGRENADE"
}
Config.ItemLoot = {
	"yusuf",
	"grip",
	"flashlight",
	"suppressor",
	"binoculars",
	"boxpistol",
	"boxsmg",
	"boxshot",
	"boxrifle",
	"boxflare",
	"oxygenmask",
	"repairkit",
	"boxsniper",
	"bulletproof",
	"boxmg",
	'bandage',
	'bandage2',
	'medikit',
	'asbo',
	'blista',
	'brioso',
	'club',
	'dilettante',
	'dilettante2',
	'kanjo',
	'issi2',
	'issi3',
	'panto',
	'prairie',
	'rhapsody',
	'brioso2',
	'weevil',
	'cogcabrio',
	'exemplar',
	'f620',
	'felon',
	'felon2',
	'jackal',
	'oracle',
	'oracle2',
	'sentinel',	
	'sentinel2',
	'windsor',
	'windsor2',
	'zion',
	'zion2',
	'bmx',
	'cruiser',
	'fixter',
	'scorcher',
}

Config.CarsLoot = {
	'bruiser',
	'bruiser2',
	'bruiser3',
	'brutus',
	'brutus2',
	'brutus3',
	'deathbike',
	'deathbike2',
	'deathbike3',
	'deviant',
	'impaler',
	'impaler2',
	'impaler3',
	'impaler4',
	'imperator',
	'imperator2',
	'imperator3',
	'issi4',
	'issi5',
	'issi6',
	'monster3',
	'monster4',
	'monster5',
	'slamvan4',
	'slamvan5',
	'slamvan6',
	'tulip',
	'vamos',
	'zr380',
	'zr3802',
	'zr3803',
	'dominator4',
	'dominator5',
	'dominator6',
	'cerberus',
	'cerberus2',
	'cerberus3',
	'scarab',
	'scarab2',
	'scarab3',
}



Config.ObjectDropLoot = true --false if you experience low performance of server
Config.ObjectsLoot = { -- objects in here can be looted around the map
	"prop_bin_01a",
	"prop_bin_02a",
	"prop_bin_05a",
	"prop_bin_08a",
	"prop_bin_08open",
	"p_dumpster_t",
	"prop_cs_dumpster_01a",
	"prop_dumpster_01a",
	"prop_dumpster_02a",
	"prop_dumpster_02b",
	"prop_dumpster_3a",
	"prop_dumpster_4a",
	"prop_dumpster_4b"
}

Config.ProbabilityWeaponLootObject = 4 --4%
Config.ProbabilityItemLootObject = 22 -- 18%
Config.ProbabilityMoneyLootObject = 52 -- 26%

Config.WeaponLootObject ={
	"WEAPON_PISTOL",
	"WEAPON_FLASHLIGHT",
	"WEAPON_MACHETE",
	"WEAPON_NIGHTSTICK",
	"WEAPON_BAT",
	"WEAPON_STUNGUN",
	"WEAPON_MICROSMG",
	"WEAPON_PUMPSHOTGUN",
	"WEAPON_GRENADE",
	"WEAPON_BALL",
}
Config.ItemLootObject = {
	'bandage',
	'medikit',
	'asbo',
	'blista',
	'brioso',
	'club',
	'dilettante',
	'dilettante2',
	'kanjo',
	'issi2',
	'issi3',
	'panto',
	'prairie',
	'rhapsody',
	'brioso2',
	'weevil',
	'cogcabrio',
	'exemplar',
	'f620',
	'felon',
	'felon2',
	'jackal',
	'oracle',
	'oracle2',
	'sentinel',
	'sentinel2',
	'windsor',
	'windsor2',
	'zion',
	'zion2',
	'bmx',
	'cruiser',
	'fixter',
	'scorcher',
}
Config.CarsObject = {
	'bruiser',
	'bruiser2',
	'bruiser3',
	'brutus',
	'brutus2',
	'brutus3',
	'deathbike',
	'deathbike2',
	'deathbike3',
	'deviant',
	'impaler',
	'impaler2',
	'impaler3',
	'impaler4',
	'imperator',
	'imperator2',
	'imperator3',
	'issi4',
	'issi5',
	'issi6',
	'monster3',
	'monster4',
	'monster5',
	'slamvan4',
	'slamvan5',
	'slamvan6',
	'tulip',
	'vamos',
	'zr380',
	'zr3802',
	'zr3803',
	'dominator4',
	'dominator5',
	'dominator6',
	'cerberus',
	'cerberus2',
	'cerberus3',
	'scarab',
	'scarab2',
	'scarab3',
}
Config.CarsLootObject = {
'asbo',
'blista',
'brioso',
'club',
'dilettante',
'dilettante2',
'kanjo',
'issi2',
'issi3',
'panto',
'prairie',
'rhapsody',
'brioso2',
'weevil',
'cogcabrio',
'exemplar',
'f620',
'felon',
'felon2',
'jackal',
'oracle',
'oracle2',
'sentinel',
'sentinel2',
'windsor',
'windsor2',
'zion',
'zion2',
'bmx',
'cruiser',
'fixter',
'scorcher',
}

Config.NoPeds = true
Config.Blackout = false
Config.MuteAmbience = true
Config.NotHealthRecharge = true
Config.SafeZone = true
Config.SafeZoneRadioBlip = false
Config.SafeZoneCoords = {
	{x = 453.86, y = -1018.96, z = 28.41, radio = 100.0}
}

Config.Debug = false
